### ISSUE TITLE
첫 실행 시 오류 발생

### ISSUE THREAD

**Issue by yj0524** [kimcore/chzzk#3]
```
node_modules/chzzk/dist/chat/chat.js:146
                    for (const chat of chats) {
                                       ^

TypeError: chats is not iterable
    at ChzzkChat.<anonymous> (node_modules/chzzk/dist/chat/chat.js:146:40)
    at Generator.next (<anonymous>)
    at node_modules/chzzk/dist/chat/chat.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (node_modules/chzzk/dist/chat/chat.js:4:12)
    at ChzzkChat.handleMessage (node_modules/chzzk/dist/chat/chat.js:124:16)
    at callListener (node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onMessage (node_modules/ws/lib/event-target.js:209:9)
    at WebSocket.emit (node:events:517:28)
    at Receiver.receiverOnMessage (node_modules/ws/lib/websocket.js:1203:20)
```

Node.js 18, 19, 20, 21 모두 오류가 발생합니다.

**Comment by kimcore** [comment]
`1.0.10` 버전에서 해결되었습니다. 제보 감사합니다!
