### ISSUE TITLE
JSON Parse error: Unexpected identifier "undefined"

### ISSUE THREAD

**Issue by yj0524** [kimcore/chzzk#8]
Node.js v21.5.0
```javascript
undefined:1
undefined
^

SyntaxError: "undefined" is not valid JSON
    at JSON.parse (<anonymous>)
    at /node_modules/chzzk/dist/api/live.js:48:55
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /index.js:41:24

Node.js v21.5.0
```

---

Bun v1.0.21
```javascript
43 |                 const livePlaybackJson = content['livePlaybackJson'];
44 |                 const livePlayback = livePlaybackJson ? JSON.parse(livePlaybackJson) : null;
45 |                 delete content['livePlaybackJson'];
46 |                 const channel = content['channel'];
47 |                 const channelLivePollingStatusJson = channel['livePollingStatusJson'];
48 |                 const channelLivePollingStatus = JSON.parse(channelLivePollingStatusJson);
                                                      ^
SyntaxError: JSON Parse error: Unexpected identifier "undefined"
      at /node_modules/chzzk/dist/api/live.js:48:50
      at processTicksAndRejections (:61:77)
```

---

1.1.1 버전까지는 발생하지 않던 오류였으나, 1.1.2 버전에서 오류가 발생합니다.
- 문제가 발생하는 코드
```javascript
const liveDetail = await client.live.detail(channel.channelId);
```

**Comment by kimcore** [comment]
`1.1.3` 버전에서 해결되었습니다. 제보 감사합니다!
